input_dir: ../../
output_dir: ../../
ib:  
  - inputs: 
      - Tchap/Modules/
    outputs:
      - templateName: scenes-swift4
        output: Tchap/Generated/Storyboards.swift
  - inputs: 
#      - Riot/Modules/Call/Dialpad
      - Riot/Modules/CallTransfer
      - Riot/Modules/ContextMenu
      - Riot/Modules/CreateRoom
      - Riot/Modules/CrossSigning
      - Riot/Modules/Integrations
      - Riot/Modules/KeyBackup
      - Riot/Modules/KeyVerification
      - Riot/Modules/QRCode
      - Riot/Modules/Reauthentication
      - Riot/Modules/Room
      - Riot/Modules/Rooms
      - Riot/Modules/Secrets
      - Riot/Modules/SecureBackup
      - Riot/Modules/ServiceTerms
      - Riot/Modules/SetPinCode
      - Riot/Modules/Settings
      - Riot/Modules/SideMenu
      - Riot/Modules/SlidingModal
      - Riot/Modules/Spaces
      - Riot/Modules/Threads
    filter: ^((?!DeactivateAccountViewController).)*\.(storyboard)
    outputs:
      - templatePath: Templates/IB/scenes-riot-swift4.stencil
        output: Tchap/Generated/Storyboards_Riot.swift
strings:
  inputs: Tchap/Assets/Localizations/fr.lproj/Tchap.strings
  outputs:
      templatePath: Templates/Strings/flat-swift4-vector.stencil
      output: Tchap/Generated/Strings.swift
      params:
        className: TchapL10n
        publicAccess: true
xcassets:  
  - inputs:
      - Tchap/Assets/Images.xcassets  
      - Tchap/Assets/SharedImages.xcassets
    outputs:
      - templatePath: Templates/Assets/swift4-tchap.stencil
        output: Tchap/Generated/Images.swift
  - inputs:
      - Riot/Assets/Images.xcassets  
      - Riot/Assets/SharedImages.xcassets
    outputs:
      - templatePath: Templates/Assets/swift4-element.stencil
        output: Tchap/Generated/Images_Riot.swift
plist:
  - inputs: Tchap/SupportingFiles/Info.plist
    outputs:
      templateName: runtime-swift4
      output: Tchap/Generated/InfoPlist.swift
      params:
        enumName: InfoPlist
  - inputs: Btchap/SupportingFiles/Info.plist
    outputs:
      templateName: runtime-swift4
      output: Btchap/Generated/InfoPlist.swift
      params:
        enumName: InfoPlist
  - inputs: DevTchap/SupportingFiles/Info.plist
    outputs:
      templateName: runtime-swift4
      output: DevTchap/Generated/InfoPlist.swift
      params:
        enumName: InfoPlist
